"""
Golden regression test suite for Korean PII detection.
=======================================================

Tests the detection performance of the Stage-1 (regex + checksum) engine
against the deterministic synthetic Korean PII corpus.  Any rule change that
drops precision or recall below the floors pinned here will cause CI to fail,
preventing silent detection regressions.

Run (single command, produces pass/fail):
    pytest tests/test_korean_pii_regression.py -v

Verbose summary (prints full metrics table even on pass):
    pytest tests/test_korean_pii_regression.py -v -s

Coverage
--------
* 5 Korean PII categories:  PHONE, RRN, KR_ACCOUNT, PERSON, ADDRESS
* 37 positive format variants (per source_tag in KoreanPIICorpus seed=42)
* 36 negative samples used as the false-positive gate
* Per-category aggregate precision / recall floors
* Per-format-variant recall floor (catches targeted regressions)
* Known gaps documented explicitly (no silent pass-through)

How to update golden thresholds
---------------------------------
When a rule improvement intentionally raises precision or recall:

  1. Run: pytest tests/test_korean_pii_regression.py -v -s
     and confirm the new metrics in the summary table.
  2. Update the threshold constants in this file.
  3. Sign the rule-set change via update-manifest (see updater.py).
  4. Open a PR with the detection-rule changelog entry.

This file is part of the control plane — it must never be modified by an
automated agent.  Pin-list and threshold edits require out-of-band user review.

Baseline measurements (corpus seed=42, samples_per_format=5, Stage-1 only)
---------------------------------------------------------------------------
  PHONE       recall=1.000  precision=1.000
  RRN         recall=1.000  precision=1.000
  KR_ACCOUNT  recall=1.000  precision=0.984
  PERSON      recall=0.556  precision=1.000   [known gaps: sentence, en-label]
  ADDRESS     recall=0.840  precision=1.000

Known detection gaps (Stage-1 regex limitations — require Stage-2 NER):
  * PERSON — English-label format ("Name: 김철수"):
        Stage-1 person_labeled_en only matches Western capitalised names;
        Korean-script names after an English label are a Stage-2 gap.
  * PERSON — Sentence context ("고객 김철수님께서 요청하셨습니다."):
        Stage-1 has no unlabelled Korean person-name NER; Stage-2 required.
  * ADDRESS — Labelled format ("주소: <addr>"):
        The address_kr regex sometimes requires province-suffix words (도/시)
        to appear before the street token; bare province names miss some forms.
"""

from __future__ import annotations

import textwrap
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict, FrozenSet, List, Optional, Set, Tuple

import pytest

from pii_guard import Engine
from pii_guard.corpus import KoreanPIICorpus, CorpusSample
from pii_guard.corpus.korean_pii import compute_precision_recall

# ─────────────────────────────────────────────────────────────────────────────
# Constants — corpus configuration (must be stable across runs)
# ─────────────────────────────────────────────────────────────────────────────

_CORPUS_SEED: int = 42
_SAMPLES_PER_FORMAT: int = 5

# ─────────────────────────────────────────────────────────────────────────────
# Golden thresholds
# ─────────────────────────────────────────────────────────────────────────────
# Aggregate category floors
# Format: (min_recall, min_precision)
GOLDEN_AGGREGATE: Dict[str, Tuple[float, float]] = {
    "PHONE":      (0.90, 0.90),
    "RRN":        (0.90, 0.90),
    "KR_ACCOUNT": (0.90, 0.90),
    "PERSON":     (0.50, 0.85),   # lower recall — sentence/en-label are known gaps
    "ADDRESS":    (0.75, 0.85),
}

# Per-format-variant recall floors.
# Keys are the source_tag values generated by KoreanPIICorpus.
# A format variant below its floor signals a targeted regression.
# Use 0.0 to document a KNOWN GAP without failing CI.
GOLDEN_FORMAT_RECALL: Dict[str, float] = {
    # ── PHONE ─────────────────────────────────────────────────────────────────
    "phone_mobile_dash":        0.80,
    "phone_mobile_bare":        0.80,
    "phone_landline":           0.80,
    "phone_international":      0.80,
    "phone_mobile_dot":         0.80,
    "phone_inline_sentence":    0.80,
    # ── RRN ───────────────────────────────────────────────────────────────────
    "rrn_dash":                 0.80,
    "rrn_bare":                 0.80,
    "rrn_gender1":              0.80,
    "rrn_gender2":              0.80,
    "rrn_gender3":              0.80,
    "rrn_inline_form":          0.80,
    "rrn_space":                0.80,
    # ── KR_ACCOUNT ────────────────────────────────────────────────────────────
    "kr_acct_kookmin_kr_label": 0.80,
    "kr_acct_kookmin_en_label": 0.80,
    "kr_acct_kookmin_inline":   0.80,
    "kr_acct_shinhan_kr_label": 0.80,
    "kr_acct_shinhan_en_label": 0.80,
    "kr_acct_shinhan_inline":   0.80,
    "kr_acct_woori_kr_label":   0.80,
    "kr_acct_woori_en_label":   0.80,
    "kr_acct_woori_inline":     0.80,
    "kr_acct_hana_kr_label":    0.80,
    "kr_acct_hana_en_label":    0.80,
    "kr_acct_hana_inline":      0.80,
    # ── PERSON ────────────────────────────────────────────────────────────────
    "person_성명_label":         0.80,
    "person_이름_label":         0.80,
    "person_담당자_label":        0.80,
    "person_신청인_label":        0.80,
    "person_작성자_label":        0.80,
    # KNOWN GAPS — Stage-1 cannot detect these; set to 0.0 to document without failing
    "person_name_en_label":     0.00,   # KNOWN GAP: Korean name after English label
    "person_sentence":          0.00,   # KNOWN GAP: unlabelled sentence context
    # ── ADDRESS ───────────────────────────────────────────────────────────────
    "address_bare":             0.80,
    "address_residence":        0.80,
    "address_labeled":          0.50,   # 60% baseline; lower floor for variant robustness
    "address_en_label":         0.60,
    "address_delivery":         0.60,
}

# False-positive caps for negative sample subsets
# Maximum allowed FPs across each negative-sample group
GOLDEN_FP_CAPS: Dict[str, int] = {
    "neg_person":       0,   # no false PERSON detections allowed
    "neg_phone":        0,   # no false PHONE detections allowed
    "neg_rrn":          1,   # 1 known FP: FOREIGN_REG fires on '주문: 1234567890123'
                             # (13 digits whose 7th digit is in the 5-8 foreign range).
                             # This is FOREIGN_REG, NOT RRN — test_no_false_rrn_detections_on_invalid_rrns
                             # separately ensures the RRN detector itself does NOT fire here.
    "neg_address":      0,
    "neg_kr_account":   1,   # 1 known FP: 4-3-6 pattern matches "코드번호: 1000-100-100000"
    "neg_clean":        0,
}

# Total FP cap across ALL negative samples (any category)
GOLDEN_TOTAL_FP_CAP: int = 3   # current baseline is 2; allow 1 slack

# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class FormatMetrics:
    """Recall metrics for one format variant (source_tag)."""
    tag: str
    total: int
    detected: int
    categories: FrozenSet[str]

    @property
    def recall(self) -> float:
        return self.detected / self.total if self.total else 0.0

    def __str__(self) -> str:
        cats = ",".join(sorted(self.categories))
        return (
            f"{self.tag:<40} [{cats}]  "
            f"{self.detected}/{self.total} = {self.recall:.0%}"
        )


@dataclass
class CategoryMetrics:
    """Aggregate precision/recall for one category."""
    category: str
    precision: float
    recall: float
    n_positive: int
    n_negative: int


@dataclass
class FalsePositiveRecord:
    """A single false positive detection on a negative sample."""
    source_tag: str
    text: str
    detected_categories: List[str]


@dataclass
class RegressionReport:
    """Full regression run results — built once per session."""
    format_metrics: Dict[str, FormatMetrics] = field(default_factory=dict)
    category_metrics: Dict[str, CategoryMetrics] = field(default_factory=dict)
    false_positives: List[FalsePositiveRecord] = field(default_factory=list)
    fp_by_neg_group: Dict[str, int] = field(default_factory=lambda: defaultdict(int))
    known_gap_tags: Set[str] = field(default_factory=set)

    def summary_table(self) -> str:
        """Human-readable metrics table for -s / verbose output."""
        lines = [
            "",
            "┌─────────────────────────────────────────────────────────────────────┐",
            "│       Korean PII Detection — Golden Regression Report               │",
            "├───────────────┬──────────────────┬──────────────────────────────────┤",
            "│ Category      │ Recall (floor)   │ Precision (floor)                │",
            "├───────────────┼──────────────────┼──────────────────────────────────┤",
        ]
        for cat, cm in sorted(self.category_metrics.items()):
            r_floor, p_floor = GOLDEN_AGGREGATE.get(cat, (0.0, 0.0))
            r_ok = "✓" if cm.recall >= r_floor else "✗"
            p_ok = "✓" if cm.precision >= p_floor else "✗"
            lines.append(
                f"│ {cat:<13} │ {cm.recall:.3f} {r_ok} (≥{r_floor:.2f})  "
                f"│ {cm.precision:.3f} {p_ok} (≥{p_floor:.2f})              │"
            )
        lines.append(
            "├───────────────┴──────────────────┴──────────────────────────────────┤"
        )
        lines.append("│ Per-format recall (format_tag : detected/total = recall)            │")
        lines.append("├──────────────────────────────────────────────────────────────────────┤")
        for tag, fm in sorted(self.format_metrics.items()):
            floor = GOLDEN_FORMAT_RECALL.get(tag, 0.0)
            ok = "✓" if fm.recall >= floor else "✗"
            gap = " [KNOWN GAP]" if tag in self.known_gap_tags else ""
            lines.append(
                f"│  {ok} {fm.tag:<38} {fm.detected}/{fm.total} = {fm.recall:.0%}"
                f" (≥{floor:.0%}){gap:<13}│"
            )
        lines.append("├──────────────────────────────────────────────────────────────────────┤")
        total_fps = len(self.false_positives)
        lines.append(f"│ False positives on negatives: {total_fps} (cap: ≤{GOLDEN_TOTAL_FP_CAP})                    │")
        for fp in self.false_positives:
            truncated = fp.text[:40]
            cats = ",".join(fp.detected_categories)
            lines.append(f"│  [{fp.source_tag}] {truncated!r} => {cats}")
        lines.append("└──────────────────────────────────────────────────────────────────────┘")
        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Session-scoped regression runner
# ─────────────────────────────────────────────────────────────────────────────

def _build_regression_report(corpus: KoreanPIICorpus, engine: Engine) -> RegressionReport:
    """
    Run the engine over the full corpus once and build a RegressionReport.

    This is called at most once per pytest session via the session-scoped
    fixture below.
    """
    report = RegressionReport()

    # Identify known-gap tags
    report.known_gap_tags = {
        tag for tag, floor in GOLDEN_FORMAT_RECALL.items() if floor == 0.0
    }

    # ── Per-format-variant recall ─────────────────────────────────────────────
    tag_total: Dict[str, int] = defaultdict(int)
    tag_detected: Dict[str, int] = defaultdict(int)
    tag_cats: Dict[str, Set[str]] = defaultdict(set)

    for sample in corpus.positive_samples():
        tag = sample.source_tag
        result = engine.scan(sample.text)
        detected_cats = {d.category for d in result.detections}
        tag_total[tag] += 1
        tag_cats[tag].update(sample.categories)
        if any(cat in detected_cats for cat in sample.categories):
            tag_detected[tag] += 1

    for tag in tag_total:
        report.format_metrics[tag] = FormatMetrics(
            tag=tag,
            total=tag_total[tag],
            detected=tag_detected[tag],
            categories=frozenset(tag_cats[tag]),
        )

    # ── Aggregate precision / recall per category ─────────────────────────────
    def detect_fn(text: str) -> Set[str]:
        res = engine.scan(text)
        return {d.category for d in res.detections}

    all_cats = set(GOLDEN_AGGREGATE.keys())
    for cat in sorted(all_cats):
        p, r = compute_precision_recall(corpus, detect_fn, cat)
        report.category_metrics[cat] = CategoryMetrics(
            category=cat,
            precision=p,
            recall=r,
            n_positive=len(corpus.samples_for_category(cat)),
            n_negative=len(corpus.negative_samples()),
        )

    # ── False positives on negative samples ───────────────────────────────────
    for sample in corpus.negative_samples():
        result = engine.scan(sample.text)
        if result.detections:
            cats = [d.category for d in result.detections]
            report.false_positives.append(FalsePositiveRecord(
                source_tag=sample.source_tag,
                text=sample.text,
                detected_categories=cats,
            ))
            report.fp_by_neg_group[sample.source_tag] += 1

    return report


@pytest.fixture(scope="session")
def korean_corpus() -> KoreanPIICorpus:
    """Deterministic Korean PII corpus (seed=42, 5 samples/format)."""
    return KoreanPIICorpus(seed=_CORPUS_SEED, samples_per_format=_SAMPLES_PER_FORMAT)


@pytest.fixture(scope="session")
def stage1_engine() -> Engine:
    """Stage-1 only Engine (no Stage-2 NER subprocess)."""
    return Engine()


@pytest.fixture(scope="session")
def regression_report(korean_corpus: KoreanPIICorpus, stage1_engine: Engine) -> RegressionReport:
    """
    Full regression report — computed once for the session.

    All test classes consume this fixture so the corpus is only scanned once.
    """
    return _build_regression_report(korean_corpus, stage1_engine)


# ─────────────────────────────────────────────────────────────────────────────
# Test classes
# ─────────────────────────────────────────────────────────────────────────────

class TestAggregateThresholds:
    """
    Category-level precision / recall must stay above the golden floors.

    A failing test here means an across-the-board regression in at least one
    category.  Check per-format tests for the specific variant that regressed.
    """

    @pytest.mark.parametrize("category,floors", sorted(GOLDEN_AGGREGATE.items()))
    def test_recall_floor(
        self,
        regression_report: RegressionReport,
        category: str,
        floors: Tuple[float, float],
    ) -> None:
        min_recall, _ = floors
        cm = regression_report.category_metrics[category]
        assert cm.recall >= min_recall, (
            f"{category} recall REGRESSION: "
            f"got {cm.recall:.3f}, floor is {min_recall:.3f}  "
            f"({cm.n_positive} positive samples)"
        )

    @pytest.mark.parametrize("category,floors", sorted(GOLDEN_AGGREGATE.items()))
    def test_precision_floor(
        self,
        regression_report: RegressionReport,
        category: str,
        floors: Tuple[float, float],
    ) -> None:
        _, min_precision = floors
        cm = regression_report.category_metrics[category]
        assert cm.precision >= min_precision, (
            f"{category} precision REGRESSION (over-detection): "
            f"got {cm.precision:.3f}, floor is {min_precision:.3f}  "
            f"({cm.n_negative} negative samples used)"
        )

    def test_all_categories_measured(self, regression_report: RegressionReport) -> None:
        """Every category defined in GOLDEN_AGGREGATE must have a measurement."""
        for cat in GOLDEN_AGGREGATE:
            assert cat in regression_report.category_metrics, (
                f"Category {cat!r} has a golden threshold but no measurement. "
                f"Ensure the corpus contains samples for it."
            )


class TestFormatVariantRecall:
    """
    Per-format-variant recall floors.

    Each parametrised test covers one source_tag format.  A failure here
    tells you exactly which surface form of a category regressed, which
    narrows the root-cause to a specific regex change.

    Format variants with floor=0.0 are KNOWN GAPS (Stage-1 cannot detect them
    without NER).  They are listed here to document coverage, not to gate CI.
    Their tests always pass regardless of detection rate.
    """

    @pytest.mark.parametrize("tag,floor", sorted(GOLDEN_FORMAT_RECALL.items()))
    def test_format_recall(
        self,
        regression_report: RegressionReport,
        tag: str,
        floor: float,
    ) -> None:
        if tag not in regression_report.format_metrics:
            if floor == 0.0:
                pytest.skip(f"Format tag {tag!r} not present in corpus (known gap)")
            else:
                pytest.fail(
                    f"Format tag {tag!r} has floor {floor} but no corpus samples were found. "
                    f"The corpus generator may have changed. Check KoreanPIICorpus._build()."
                )

        fm = regression_report.format_metrics[tag]

        if floor == 0.0:
            # Known gap — document the actual rate but never fail
            return

        assert fm.recall >= floor, (
            f"Format variant REGRESSION: {tag!r}  "
            f"recall={fm.recall:.3f} < floor={floor:.3f}  "
            f"({fm.detected}/{fm.total} detected)  "
            f"Category: {','.join(sorted(fm.categories))}"
        )

    def test_all_format_tags_have_thresholds(
        self, regression_report: RegressionReport
    ) -> None:
        """
        Every format tag in the corpus must have an entry in GOLDEN_FORMAT_RECALL.

        Failure here means a new format variant was added to the corpus without
        a corresponding golden threshold — add one (or 0.0 for known gaps).
        """
        missing = set(regression_report.format_metrics.keys()) - set(GOLDEN_FORMAT_RECALL.keys())
        assert not missing, (
            f"New format tags found in corpus without golden thresholds: {sorted(missing)}\n"
            f"Add each to GOLDEN_FORMAT_RECALL in this file."
        )

    def test_all_threshold_tags_exist_in_corpus(
        self, regression_report: RegressionReport
    ) -> None:
        """
        Every tag in GOLDEN_FORMAT_RECALL (with floor > 0) must appear in the corpus.

        Failure means a format variant was removed from the corpus — either remove
        the threshold too, or restore the corpus generator to produce that variant.
        """
        gated_tags = {t for t, f in GOLDEN_FORMAT_RECALL.items() if f > 0.0}
        corpus_tags = set(regression_report.format_metrics.keys())
        orphaned = gated_tags - corpus_tags
        assert not orphaned, (
            f"Tags in GOLDEN_FORMAT_RECALL (floor>0) not found in corpus: {sorted(orphaned)}\n"
            f"Either the corpus no longer generates these variants, or the tag was renamed."
        )


class TestFalsePositiveGate:
    """
    Precision guard — must not exceed false-positive caps on negative samples.

    A failing test here means a rule is over-triggering.  Tighten the pattern
    or raise the min_confidence threshold for the offending rule.
    """

    def test_total_false_positives_within_cap(
        self, regression_report: RegressionReport
    ) -> None:
        total = len(regression_report.false_positives)
        assert total <= GOLDEN_TOTAL_FP_CAP, (
            f"Total false positives {total} exceeds cap {GOLDEN_TOTAL_FP_CAP}.  "
            f"Detections on negatives:\n"
            + "\n".join(
                f"  [{fp.source_tag}] {fp.text!r} => {fp.detected_categories}"
                for fp in regression_report.false_positives
            )
        )

    @pytest.mark.parametrize("neg_tag,cap", sorted(GOLDEN_FP_CAPS.items()))
    def test_fp_cap_by_negative_group(
        self,
        regression_report: RegressionReport,
        neg_tag: str,
        cap: int,
    ) -> None:
        actual = regression_report.fp_by_neg_group.get(neg_tag, 0)
        assert actual <= cap, (
            f"False-positive cap exceeded for negative group {neg_tag!r}: "
            f"{actual} > {cap}.  "
            f"FP samples:\n"
            + "\n".join(
                f"  {fp.text!r} => {fp.detected_categories}"
                for fp in regression_report.false_positives
                if fp.source_tag == neg_tag
            )
        )

    def test_no_false_person_detections(
        self, regression_report: RegressionReport
    ) -> None:
        """PERSON must never fire on any negative sample (high-precision check)."""
        person_fps = [
            fp for fp in regression_report.false_positives
            if "PERSON" in fp.detected_categories
        ]
        assert not person_fps, (
            f"PERSON fired on {len(person_fps)} negative sample(s):\n"
            + "\n".join(f"  [{fp.source_tag}] {fp.text!r}" for fp in person_fps)
        )

    def test_no_false_rrn_detections_on_invalid_rrns(
        self, regression_report: RegressionReport
    ) -> None:
        """
        RRN detector must not fire on the explicitly-invalid RRN negatives.

        The neg_rrn samples contain 13-digit strings that fail the checksum or
        have an invalid gender digit.  A FOREIGN_REG match on some of these is
        acceptable (different category); a RRN match is a checksum regression.
        """
        rrn_fps_on_neg_rrn = [
            fp for fp in regression_report.false_positives
            if fp.source_tag == "neg_rrn" and "RRN" in fp.detected_categories
        ]
        assert not rrn_fps_on_neg_rrn, (
            f"RRN detector fired on explicitly-invalid RRN negatives "
            f"({len(rrn_fps_on_neg_rrn)} samples). This is a checksum regression:\n"
            + "\n".join(f"  {fp.text!r}" for fp in rrn_fps_on_neg_rrn)
        )


class TestKnownGapsDocumented:
    """
    Verify that known Stage-1 coverage gaps exist and are properly documented.

    These tests PASS when the gap still exists (no false assurance).  If
    Stage-2 NER is later wired in, update GOLDEN_FORMAT_RECALL floors
    for the gap tags to a non-zero value.
    """

    def test_person_english_label_is_gap(
        self, regression_report: RegressionReport
    ) -> None:
        """
        Stage-1 cannot detect "Name: 김철수" because the labeled_en regex
        matches only Western capitalised names.  This is the documented gap.
        When Stage-2 NER is wired in for PERSON, update this test.
        """
        fm = regression_report.format_metrics.get("person_name_en_label")
        if fm is None:
            pytest.skip("No person_name_en_label samples in corpus")
        # We expect recall < 100% — if it becomes perfect, we should update thresholds
        # to a higher floor and remove this known-gap test.
        # For now, simply confirm the gap is documented (floor=0.0 in GOLDEN_FORMAT_RECALL).
        assert GOLDEN_FORMAT_RECALL.get("person_name_en_label", -1.0) == 0.0, (
            "person_name_en_label is unexpectedly gated at > 0.0. "
            "If Stage-1 now handles this format, raise the floor and remove this test."
        )

    def test_person_sentence_context_is_gap(
        self, regression_report: RegressionReport
    ) -> None:
        """
        Stage-1 cannot detect person names in unlabelled sentence context.
        This requires NER (Stage-2).  Documented as a known gap.
        """
        fm = regression_report.format_metrics.get("person_sentence")
        if fm is None:
            pytest.skip("No person_sentence samples in corpus")
        assert GOLDEN_FORMAT_RECALL.get("person_sentence", -1.0) == 0.0, (
            "person_sentence is unexpectedly gated. "
            "If NER is now active, update the floor and remove this test."
        )

    def test_known_gaps_never_silently_pass(
        self, regression_report: RegressionReport
    ) -> None:
        """
        Coverage gaps are explicitly declared — there must be NO format variant
        missing from GOLDEN_FORMAT_RECALL that also has zero recall.

        A variant with 0% recall and no floor entry would be an undocumented
        silent coverage gap — violating the NoSilentGap policy.
        """
        silent_gaps = []
        for tag, fm in regression_report.format_metrics.items():
            if fm.recall == 0.0 and tag not in GOLDEN_FORMAT_RECALL:
                silent_gaps.append(tag)
        assert not silent_gaps, (
            f"Undocumented zero-recall format variants detected — these are silent gaps:\n"
            + "\n".join(f"  {t}" for t in sorted(silent_gaps))
            + "\nAdd each to GOLDEN_FORMAT_RECALL with floor=0.0 and document the gap."
        )


class TestHighSeverityFloor:
    """
    High-severity categories (RRN, blocking categories) must maintain
    especially high recall floors even when other categories degrade.

    The GracefulDegradation policy says: "high-severity still caught" even
    when Stage-2 fails.  Stage-1 must be the backstop for these categories.
    """

    def test_rrn_recall_high_floor(self, regression_report: RegressionReport) -> None:
        """RRN recall must be ≥ 0.90 for Stage-1 to serve as fail-safe backstop."""
        cm = regression_report.category_metrics["RRN"]
        assert cm.recall >= 0.90, (
            f"RRN recall {cm.recall:.3f} < 0.90.  "
            f"RRN is a high-severity blocking category — Stage-1 must reliably catch it. "
            f"({cm.n_positive} positive samples)"
        )

    def test_rrn_precision_high_floor(self, regression_report: RegressionReport) -> None:
        """RRN precision must be ≥ 0.90 to avoid blocking on valid non-PII inputs."""
        cm = regression_report.category_metrics["RRN"]
        assert cm.precision >= 0.90, (
            f"RRN precision {cm.precision:.3f} < 0.90.  "
            f"Over-detection blocks legitimate requests. ({cm.n_negative} negative samples)"
        )

    @pytest.mark.parametrize("tag", [
        "rrn_dash", "rrn_bare", "rrn_space",
        "rrn_gender1", "rrn_gender2", "rrn_gender3",
    ])
    def test_rrn_format_variants_detected(
        self, regression_report: RegressionReport, tag: str
    ) -> None:
        """Every RRN surface form must be caught at high recall."""
        fm = regression_report.format_metrics.get(tag)
        assert fm is not None, f"RRN variant {tag!r} not found in corpus"
        assert fm.recall >= 0.80, (
            f"RRN format variant {tag!r} recall dropped to {fm.recall:.3f} "
            f"({fm.detected}/{fm.total}).  Check _RRN_PATTERN regex."
        )


class TestRegressionSummary:
    """
    Summary / reporting — always runs and prints the full metrics table.

    These tests do not assert additional thresholds; they produce human-readable
    output when running with ``-s``.  The table is the canonical evidence that
    detection efficacy was verified before a rule-set update is merged.
    """

    def test_print_summary_report(
        self,
        regression_report: RegressionReport,
        capsys,
    ) -> None:
        """Print the full regression report.  Always passes; read the output."""
        print(regression_report.summary_table())
        # Capture and check the report was non-empty
        captured = capsys.readouterr()
        assert "Korean PII Detection" in captured.out, (
            "Summary table was not printed — check the RegressionReport.summary_table() method"
        )

    def test_corpus_sizes_stable(self, korean_corpus: KoreanPIICorpus) -> None:
        """
        Corpus total sample count must be stable across runs.

        If this fails, the KoreanPIICorpus generator changed structure (new
        format variants or removed ones).  Update GOLDEN_FORMAT_RECALL accordingly.
        """
        pos = len(korean_corpus.positive_samples())
        neg = len(korean_corpus.negative_samples())
        # seed=42, samples_per_format=5 → 195 pos + 36 neg = 231 total
        # Breakdown: PERSON 45 + PHONE 30 + RRN 35 + ADDRESS 25 + KR_ACCOUNT 60 = 195
        assert pos >= 190, f"Fewer positive samples than expected: {pos} < 190"
        assert neg >= 30, f"Fewer negative samples than expected: {neg} < 30"
        # Allow slight growth (new format variants) but not shrinkage
        assert pos <= 500, f"Suspiciously many positive samples: {pos}"

    def test_category_counts_stable(self, korean_corpus: KoreanPIICorpus) -> None:
        """
        Per-category counts must match the corpus generator's documented output.
        If this fails, format variants were added or removed.
        """
        counts = korean_corpus.category_counts()
        expected_minimums = {
            "PERSON":     45,   # 9 format groups × 5
            "PHONE":      30,   # 6 format groups × 5
            "RRN":        35,   # 7 format groups × 5
            "ADDRESS":    25,   # 5 format groups × 5
            "KR_ACCOUNT": 60,   # 4 banks × 3 label styles × 5
        }
        for cat, minimum in expected_minimums.items():
            actual = counts.get(cat, 0)
            assert actual >= minimum, (
                f"{cat} category count {actual} < minimum {minimum}.  "
                f"Corpus generator may have dropped a format variant."
            )

    def test_regression_report_is_complete(
        self, regression_report: RegressionReport
    ) -> None:
        """All expected format tags must have been measured."""
        expected_tags = {t for t, f in GOLDEN_FORMAT_RECALL.items() if f > 0.0}
        missing = expected_tags - set(regression_report.format_metrics.keys())
        assert not missing, (
            f"Expected corpus format tags not measured: {sorted(missing)}.  "
            f"Either the corpus or the GOLDEN_FORMAT_RECALL dict needs updating."
        )
